AnimFlags = {
    { name = "Loop", value = (1<<0), },
    { name = "HoldLastFrame", value = (1<<1), },
    { name = "NotInterruptable", value = (1<<2), },
    { name = "UpperBody", value = (1<<3), },
    { name = "Secondary", value = (1<<4), },
    { name = "AbortOnPedMove", value = (1<<5), },
    { name = "Additive", value = (1<<6), },
    { name = "OverridePhysics", value = (1<<7), },
    { name = "ExtractInitialOffset", value = (1<<8), },
    { name = "ExitAfterInterrupt", value = (1<<9), },
    { name = "TagSyncIn", value = (1<<10), },
    { name = "TagSyncOut", value = (1<<11), },
    { name = "TagSyncContinuous", value = (1<<12), },
    { name = "ForceStart", value = (1<<13), },
    { name = "UseKinematicPhysics", value = (1<<14), },
    { name = "UseMoverExtraction", value = (1<<15), },
    { name = "DontSuppressLoco", value = (1<<16), },
    { name = "EndsInDeadPose", value = (1<<17), },
    { name = "ActivateRagdollOnCollision", value = (1<<18), },
    { name = "DontExitOnDeath", value = (1<<19), },
    { name = "AbortOnWeaponDamage", value = (1<<20), },
    { name = "DisableForcedPhysicsUpdate", value = (1<<21), },
    { name = "Gesture", value = (1<<22), },
    { name = "SkipIfBlockedByPrioTask", value = (1<<23), },
    { name = "UseAbsoluteMover", value = (1<<24), },
    { name = "Bit25", value = (1<<25), },
    { name = "UpperBodyTags", value = (1<<26), },
    { name = "ProcessAttachmentsOnStart", value = (1<<27), },
    { name = "ExpandPedCapsuleFromSkel", value = (1<<28), },
    { name = "BlendoutWRTLastFrame", value = (1<<29), },
    { name = "DisablePhysicalActivation", value = (1<<30), },
    { name = "DisableReleaseEvents", value = (1<<31), },
    -- { name = "Bit32", value = (1<<32), },
    -- Combo Flags
    -- Move = (1<<3)|(1<<4), -- UpperBody, Secondary
    -- MoveLoop = (1<<0)|(1<<3)|(1<<4), -- UpperBody, Secondary, Loop
}
