local Bones = {}

Bones.human_skel = {
    "skel_head",
    "skel_l_calf",
    "skel_l_clavicle",
    "skel_l_clavicle",
    "skel_l_finger00",
    "skel_l_finger01",
    "skel_l_finger02",
    "skel_l_finger10",
    "skel_l_finger11",
    "skel_l_finger12",
    "skel_l_finger13",
    "skel_l_finger20",
    "skel_l_finger21",
    "skel_l_finger22",
    "skel_l_finger23",
    "skel_l_finger30",
    "skel_l_finger31",
    "skel_l_finger32",
    "skel_l_finger33",
    "skel_l_finger40",
    "skel_l_finger41",
    "skel_l_finger42",
    "skel_l_finger43",
    "skel_l_foot",
    "skel_l_forearm",
    "skel_l_hand",
    "skel_l_thigh",
    "skel_l_toe0",
    "skel_l_toe10",
    "skel_l_toe20",
    "skel_l_upperarm",
    "skel_neck0",
    "skel_neck0",
    "skel_neck1",
    "skel_neck1",
    "skel_neck2",
    "skel_pelvis",
    "skel_r_calf",
    "skel_r_clavicle",
    "skel_r_clavicle",
    "skel_r_finger00",
    "skel_r_finger01",
    "skel_r_finger02",
    "skel_r_finger10",
    "skel_r_finger11",
    "skel_r_finger12",
    "skel_r_finger13",
    "skel_r_finger20",
    "skel_r_finger21",
    "skel_r_finger22",
    "skel_r_finger23",
    "skel_r_finger30",
    "skel_r_finger31",
    "skel_r_finger32",
    "skel_r_finger33",
    "skel_r_finger40",
    "skel_r_finger41",
    "skel_r_finger42",
    "skel_r_finger43",
    "skel_r_foot",
    "skel_r_forearm",
    "skel_r_hand",
    "skel_r_thigh",
    "skel_r_toe0",
    "skel_r_toe10",
    "skel_r_toe20",
    "skel_r_upperarm",
    "skel_spine0",
    "skel_spine0",
    "skel_spine1",
    "skel_spine2",
    "skel_spine3",
    "skel_spine3",
    "skel_spine4",
    "skel_spine5",
    "skel_spine6",
    "skel_spine_root",
    "skel_spine_root",
}

Bones.human_skel_edges = {
    { "skel_head", "skel_neck2" },
    { "skel_neck1", "skel_neck2" },
    { "skel_neck0", "skel_neck1" },
    { "skel_neck0", "skel_spine6" },
    { "skel_neck0", "skel_l_upperarm" },
    { "skel_neck0", "skel_r_upperarm" },
    { "skel_spine5", "skel_spine6" },
    { "skel_spine4", "skel_spine5" },
    { "skel_spine3", "skel_spine4" },
    { "skel_spine2", "skel_spine3" },
    { "skel_spine1", "skel_spine2" },
    { "skel_spine0", "skel_spine1" },
    { "skel_spine0", "skel_pelvis" },
    { "skel_spine_root", "skel_spine0" },
    { "skel_pelvis", "skel_l_thigh" },
    { "skel_pelvis", "skel_r_thigh" },
    { "skel_l_clavicle", "skel_l_upperarm" },
    { "skel_r_clavicle", "skel_r_upperarm" },
    { "skel_l_upperarm", "skel_l_forearm" },
    { "skel_r_upperarm", "skel_r_forearm" },
    { "skel_l_forearm", "skel_l_hand" },
    { "skel_r_forearm", "skel_r_hand" },
    { "skel_l_hand", "skel_l_finger00" },
    { "skel_l_hand", "skel_l_finger10" },
    { "skel_l_hand", "skel_l_finger20" },
    { "skel_l_hand", "skel_l_finger30" },
    { "skel_l_hand", "skel_l_finger40" },
    { "skel_r_hand", "skel_r_finger00" },
    { "skel_r_hand", "skel_r_finger10" },
    { "skel_r_hand", "skel_r_finger20" },
    { "skel_r_hand", "skel_r_finger30" },
    { "skel_r_hand", "skel_r_finger40" },
    { "skel_l_finger00", "skel_l_finger01" },
    { "skel_l_finger01", "skel_l_finger02" },
    { "skel_l_finger10", "skel_l_finger11" },
    { "skel_l_finger11", "skel_l_finger12" },
    { "skel_l_finger12", "skel_l_finger13" },
    { "skel_l_finger20", "skel_l_finger21" },
    { "skel_l_finger21", "skel_l_finger22" },
    { "skel_l_finger22", "skel_l_finger23" },
    { "skel_l_finger30", "skel_l_finger31" },
    { "skel_l_finger31", "skel_l_finger32" },
    { "skel_l_finger32", "skel_l_finger33" },
    { "skel_l_finger40", "skel_l_finger41" },
    { "skel_l_finger41", "skel_l_finger42" },
    { "skel_l_finger42", "skel_l_finger43" },
    { "skel_r_finger00", "skel_r_finger01" },
    { "skel_r_finger01", "skel_r_finger02" },
    { "skel_r_finger10", "skel_r_finger11" },
    { "skel_r_finger11", "skel_r_finger12" },
    { "skel_r_finger12", "skel_r_finger13" },
    { "skel_r_finger20", "skel_r_finger21" },
    { "skel_r_finger21", "skel_r_finger22" },
    { "skel_r_finger22", "skel_r_finger23" },
    { "skel_r_finger30", "skel_r_finger31" },
    { "skel_r_finger31", "skel_r_finger32" },
    { "skel_r_finger32", "skel_r_finger33" },
    { "skel_r_finger40", "skel_r_finger41" },
    { "skel_r_finger41", "skel_r_finger42" },
    { "skel_r_finger42", "skel_r_finger43" },
    { "skel_l_thigh", "skel_l_calf" },
    { "skel_l_calf", "skel_l_foot" },
    { "skel_l_foot", "skel_l_toe0" },
    { "skel_l_toe0", "skel_l_toe10" },
    { "skel_l_toe0", "skel_l_toe20" },
    { "skel_r_thigh", "skel_r_calf" },
    { "skel_r_calf", "skel_r_foot" },
    { "skel_r_foot", "skel_r_toe0" },
    { "skel_r_toe0", "skel_r_toe10" },
    { "skel_r_toe0", "skel_r_toe20" },
}

Bones.horse_skel = {
    "skel_head",
    "skel_l_backflap00",
    "skel_l_backflap01",
    "skel_l_backflap02",
    "skel_l_backflap03",
    "skel_l_backflap04",
    "skel_l_backflap05",
    "skel_l_bedroll",
    "skel_l_calf",
    "skel_l_clavicle",
    "skel_l_clavicle",
    "skel_l_finger00",
    "skel_l_finger01",
    "skel_l_flap",
    "skel_l_foot",
    "skel_l_forearm",
    "skel_l_frontflap00",
    "skel_l_frontflap01",
    "skel_l_frontflap02",
    "skel_l_frontflap03",
    "skel_l_frontflap04",
    "skel_l_frontflap05",
    "skel_l_hand",
    "skel_l_midflap01",
    "skel_l_midflap02",
    "skel_l_midflap03",
    "skel_l_midflap04",
    "skel_l_midflap05",
    "skel_l_satchelroot",
    "skel_l_thigh",
    "skel_l_toe0",
    "skel_l_toe1",
    "skel_l_upperarm",
    "skel_neck0",
    "skel_neck1",
    "skel_neck1",
    "skel_neck2",
    "skel_neck3",
    "skel_neck4",
    "skel_neck5",
    "skel_pelvis",
    "skel_r_backflap00",
    "skel_r_backflap01",
    "skel_r_backflap02",
    "skel_r_backflap03",
    "skel_r_backflap04",
    "skel_r_backflap05",
    "skel_r_bedroll",
    "skel_r_calf",
    "skel_r_clavicle",
    "skel_r_finger00",
    "skel_r_finger01",
    "skel_r_flap",
    "skel_r_foot",
    "skel_r_forearm",
    "skel_r_frontflap00",
    "skel_r_frontflap01",
    "skel_r_frontflap02",
    "skel_r_frontflap03",
    "skel_r_frontflap04",
    "skel_r_frontflap05",
    "skel_r_hand",
    "skel_r_midflap01",
    "skel_r_midflap02",
    "skel_r_midflap03",
    "skel_r_midflap04",
    "skel_r_midflap05",
    "skel_r_satchelroot",
    "skel_r_thigh",
    "skel_r_toe0",
    "skel_r_toe1",
    "skel_r_upperarm",
    "skel_rearseat",
    "skel_rig_tail3",
    "skel_saddle",
    "skel_spine0",
    "skel_spine1",
    "skel_spine2",
    "skel_spine3",
    "skel_spine_root",
    "skel_tail0",
    "skel_tail1",
    "skel_tail2",
    "skel_tail3",
    "skel_tail4",
}

Bones.horse_skel_edges = {
    -- Head and Neck
    { "skel_head", "skel_neck5" },
    { "skel_neck4", "skel_neck5" },
    { "skel_neck3", "skel_neck4" },
    { "skel_neck2", "skel_neck3" },
    { "skel_neck1", "skel_neck2" },
    { "skel_neck0", "skel_neck1" },
    { "skel_neck0", "skel_spine3" },

    -- Spine
    { "skel_spine3", "skel_spine_root" },
    { "skel_spine2", "skel_spine3" },
    { "skel_spine1", "skel_spine2" },
    { "skel_spine0", "skel_spine1" },
    { "skel_pelvis", "skel_spine0" },

    -- Saddle and Seats
    { "skel_spine1", "skel_saddle" },
    { "skel_pelvis", "skel_rearseat" },

    -- Pelvis and Thighs
    { "skel_pelvis", "skel_l_thigh" },
    { "skel_pelvis", "skel_r_thigh" },
    { "skel_l_thigh", "skel_l_calf" },
    { "skel_r_thigh", "skel_r_calf" },
    { "skel_l_calf", "skel_l_foot" },
    { "skel_r_calf", "skel_r_foot" },
    { "skel_l_foot", "skel_l_toe0" },
    { "skel_r_foot", "skel_r_toe0" },
    { "skel_l_toe0", "skel_l_toe1" },
    { "skel_r_toe0", "skel_r_toe1" },

    -- Clavicle and Forearm
    { "skel_spine3", "skel_l_clavicle" },
    { "skel_spine3", "skel_r_clavicle" },
    { "skel_l_clavicle", "skel_l_upperarm" },
    { "skel_r_clavicle", "skel_r_upperarm" },
    { "skel_l_upperarm", "skel_l_forearm" },
    { "skel_r_upperarm", "skel_r_forearm" },
    { "skel_l_forearm", "skel_l_hand" },
    { "skel_r_forearm", "skel_r_hand" },

    -- Hand and Fingers
    { "skel_l_hand", "skel_l_finger00" },
    { "skel_l_finger00", "skel_l_finger01" },
    { "skel_r_hand", "skel_r_finger00" },
    { "skel_r_finger00", "skel_r_finger01" },

    -- Tail
    { "skel_pelvis", "skel_tail0" },
    { "skel_tail0", "skel_tail1" },
    { "skel_tail1", "skel_tail2" },
    { "skel_tail2", "skel_tail3" },
    { "skel_tail3", "skel_tail4" },

    -- Flaps (Left and Right Back Flaps)
    -- { "skel_spine0", "skel_l_backflap00" },
    { "skel_l_backflap00", "skel_l_backflap01" },
    { "skel_l_backflap01", "skel_l_backflap02" },
    { "skel_l_backflap02", "skel_l_backflap03" },
    { "skel_l_backflap03", "skel_l_backflap04" },
    { "skel_l_backflap04", "skel_l_backflap05" },

    -- { "skel_spine0", "skel_r_backflap00" },
    { "skel_r_backflap00", "skel_r_backflap01" },
    { "skel_r_backflap01", "skel_r_backflap02" },
    { "skel_r_backflap02", "skel_r_backflap03" },
    { "skel_r_backflap03", "skel_r_backflap04" },
    { "skel_r_backflap04", "skel_r_backflap05" },

    -- Front Flaps (Left and Right)
    -- { "skel_spine1", "skel_l_frontflap00" },
    { "skel_l_frontflap00", "skel_l_frontflap01" },
    { "skel_l_frontflap01", "skel_l_frontflap02" },
    { "skel_l_frontflap02", "skel_l_frontflap03" },
    { "skel_l_frontflap03", "skel_l_frontflap04" },
    { "skel_l_frontflap04", "skel_l_frontflap05" },

    -- { "skel_spine1", "skel_r_frontflap00" },
    { "skel_r_frontflap00", "skel_r_frontflap01" },
    { "skel_r_frontflap01", "skel_r_frontflap02" },
    { "skel_r_frontflap02", "skel_r_frontflap03" },
    { "skel_r_frontflap03", "skel_r_frontflap04" },
    { "skel_r_frontflap04", "skel_r_frontflap05" },

    -- Mid Flaps (Left and Right)
    -- { "skel_spine0", "skel_l_midflap01" },
    { "skel_l_midflap01", "skel_l_midflap02" },
    { "skel_l_midflap02", "skel_l_midflap03" },
    { "skel_l_midflap03", "skel_l_midflap04" },
    { "skel_l_midflap04", "skel_l_midflap05" },

    -- { "skel_spine2", "skel_r_midflap01" },
    { "skel_r_midflap01", "skel_r_midflap02" },
    { "skel_r_midflap02", "skel_r_midflap03" },
    { "skel_r_midflap03", "skel_r_midflap04" },
    { "skel_r_midflap04", "skel_r_midflap05" },

    -- Bedroll
    { "skel_l_bedroll", "skel_r_bedroll" },
    { "skel_l_bedroll", "skel_l_satchelroot" },
    { "skel_r_bedroll", "skel_r_satchelroot" }
}

_ENV.bones = Bones
