da_trie.addOpt("devRoot", "revive", "r", function() API.revive() end, function() return IsPedDeadOrDying(PlayerPedId()) end)
da_trie.addOpt("objRoot", "revive", "r", function() API.revive() end, function() return IsPedDeadOrDying(PlayerPedId()) end)


da_trie.add("devRoot", "pos", "v")
da_trie.addOpt("pos", "cpy vec2", "2", function()
    local coords = GetEntityCoords(PlayerPedId())
    da_ui.send("clipboard", { text = ("vector2(%.3f, %.3f)"):format(coords.x, coords.y)})
end)
da_trie.addOpt("pos", "cpy vec3", "3", function()
    local coords = GetEntityCoords(PlayerPedId())
    da_ui.send("clipboard", { text = ("vector3(%.3f, %.3f, %.3f)"):format(coords.x, coords.y, coords.z)})
end)
da_trie.addOpt("pos", "cpy vec4", "4", function()
    local coords = GetEntityCoords(PlayerPedId())
    local heading = GetEntityHeading(PlayerPedId())
    da_ui.send("clipboard", { text = ("vector4(%.3f, %.3f, %.3f, %.3f)"):format(coords.x, coords.y, coords.z, heading)})
end)
